Algoritmo "SE e Senão"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Carlos Anderson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Emerson Souza
// Data atual  : 24/03/2023
Var

numero1 : real

Inicio

escreval("Digite um numero")
leia(numero1)
se(numero1 > 10)entao

  escreval("É MAIOR QUE 10!")

senao
     escreval("É MENOR OU = 10!")
fimse

Fimalgoritmo